// Generated by jextract

package eu.smogura.panama.io.posix.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sockaddr {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_SHORT.withName("sa_family"),
        MemoryLayout.sequenceLayout(14, C_CHAR).withName("sa_data")
    ).withName("sockaddr");
    public static MemoryLayout $LAYOUT() {
        return sockaddr.$struct$LAYOUT;
    }
    static final VarHandle sa_family$VH = $struct$LAYOUT.varHandle(short.class, MemoryLayout.PathElement.groupElement("sa_family"));
    public static VarHandle sa_family$VH() {
        return sockaddr.sa_family$VH;
    }
    public static short sa_family$get(MemorySegment seg) {
        return (short)sockaddr.sa_family$VH.get(seg);
    }
    public static void sa_family$set( MemorySegment seg, short x) {
        sockaddr.sa_family$VH.set(seg, x);
    }
    public static short sa_family$get(MemorySegment seg, long index) {
        return (short)sockaddr.sa_family$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sa_family$set(MemorySegment seg, long index, short x) {
        sockaddr.sa_family$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment sa_data$slice(MemorySegment seg) {
        return seg.asSlice(2, 14);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


